# download the library if they are not installed
require(devtools)
devtools::install_cran("tidyverse", quiet = TRUE)
devtools::install_github("tidymodels/tidymodels", quiet = TRUE)
devtools::install_cran("ggraph", quiet = TRUE)
devtools::install_cran("tidytext", quiet = TRUE)
devtools::install_github("michaeldorman/mapsapi", quiet = TRUE)
devtools::install_github("dkahle/ggmap", quiet = TRUE)
devtools::install_github("mapview", quiet = TRUE)
devtools::install_cran("mapview", quiet = TRUE)
devtools::install_github("lchiffon/wordcloud2", quiet = TRUE)
devtools::install_cran("e1071", quiet = TRUE)
devtools::install_cran("mapview", quiet = TRUE)
devtools::install_cran("plspm", quiet = TRUE)
devtools::install_cran("polycor", quiet = TRUE)
devtools::install_cran("ggbiplot", quiet = TRUE)
devtools::install_cran("misc3d", quiet = TRUE)
devtools::install_cran("MLmetrics", quiet = TRUE)
devtools::install_cran("shiny", quiet = TRUE)
devtools::install_cran("DT", quiet = TRUE)
devtools::install_cran("rgdal", quiet = TRUE)
devtools::install_cran("rsconnect", quiet = TRUE)
devtools::install_github("vqv/ggbiplot", quiet = TRUE)
devtools::install_cran("R.methodsS3", quiet = TRUE)
devtools::install_cran("R.oo", quiet = TRUE)
devtools::install_cran("R.utils", quiet = TRUE)
devtools::install_cran("data.table", quiet = TRUE)
devtools::install_cran("gdtools", quiet = TRUE)
devtools::install_cran("gdalUtils", quiet = TRUE)
devtools::install_cran("leaflet", quiet = TRUE)
devtools::install_cran("hexbin", quiet = TRUE)

