---
title: "data_tidy"
author: "Jungang Zou"
date: "11/9/2019"
output: github_document
---

```{r set up, include = FALSE}
# knitr will run the chunk but not include the chunk in the final document
# copy from Jeff

try(source("../dependencies.R"), silent = TRUE)

# ensure reproductivity
set.seed(10)

# load library
library(tidyverse)
library(viridis)
library(ggridges)
library(patchwork)
library(rvest)

knitr::opts_chunk$set(
  # display the code in the code truck above its results in the final document
  echo = TRUE,
  # do not display any warning messages generated by the code
  warning = FALSE,
  # set the figure to be 8 x 6, and the proportion it takes to be 90%
  fig.width = 8,
  fig.height = 6, 
  out.width = "90%"
)

# setting a global options for continuous data color family and a different format to set discrete data to have a color family
options(
  ggplot2.countinuous.colour = "viridis",
  ggplot2.countinuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

# have a minimal theme and legends at the bottom
theme_set(theme_bw() + theme(legend.position = "bottom"))
```

## reading data

```{r download}
ufo_original_data = readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-06-25/ufo_sightings.csv")

ufo_original_data
```

## Missing Value Detect

```{r detect_missing}
ufo_original_data %>% 
  map_df(.x = ., ~sum(is.na(.x))) %>% 
  knitr::kable()
```

We find the variable "state", "country", "ufo_shape" has largest number of missing values.


## Fill the missing value

According to the relationships of "city_area", "state" and "country", we can fill the missing value.

Since there are some abnormal data in "city_area" like these, we first clean the missing value:

```{r clean_city, echo = FALSE}
ufo_original_data %>% 
  select(city_area, state) %>% 
  filter(str_detect(pull(., city_area), "\\("))
```