# download the library if they are not installed
require(devtools)
devtools::install_github("tidymodels/tidymodels", quiet = TRUE)
devtools::install_cran("ggraph", quiet = TRUE)
devtools::install_cran("tidytext", quiet = TRUE)
devtools::install_github("michaeldorman/mapsapi", quiet = TRUE)
devtools::install_github("dkahle/ggmap", quiet = TRUE)
devtools::install_github("mapview", quiet = TRUE)
devtools::install_cran("mapview", quiet = TRUE)
devtools::install_github("lchiffon/wordcloud2", quiet = TRUE)
devtools::install_cran("e1071", quiet = TRUE)
devtools::install_cran("rgl", quiet = TRUE)
devtools::install_cran("FactoMineR", quiet = TRUE)
devtools::install_github("vqv/ggbiplot", quiet = TRUE)
devtools::install_cran("mapview", quiet = TRUE)
devtools::install_cran("plspm", quiet = TRUE)
devtools::install_cran("polycor", quiet = TRUE)
devtools::install_cran("misc3d", quiet = TRUE)



# load library
library(tidyverse)
library(viridis)
library(ggridges)
library(patchwork)
library(rvest)
library(tidygraph)
library(ggraph)
library(tidytext)
library(leaflet)
library(dplyr)
library(ggplot2)
library(ggmap)
library(sf)
library(mapview)
library(rgdal)
library(htmltools)
library(e1071)
library(ggbiplot)
library(FactoMineR)
