---
title: "frequency_map"
author: "J L"
date: "11/15/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(plotly)
library(tidyverse)
library(viridis)
library(ggridges)
library(leaflet)

knitr::opts_chunk$set(
  # display the code in the code truck above its results in the final document
  echo = TRUE,
  # do not display any warning messages generated by the code
  warning = FALSE,
  # set the figure to be 8 x 6, and the proportion it takes to be 90%
  fig.width = 8,
  fig.height = 6, 
  out.width = "90%"
)

# setting a global options for continuous data color family and a different format to set discrete data to have a color family
options(
  ggplot2.countinuous.colour = "viridis",
  ggplot2.countinuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

# have a minimal theme and legends at the bottom
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## read data

```{r}
ufo_data = read_csv("./data/tidied_data_final.csv", na = "")

ufo =
  ufo_data %>%  
  separate(date_time, into = c( "date","time"), sep = " " ) %>%
  separate( date, into = c("month","day","year"), sep = "/") %>% 
  mutate(a = longitude, longitude = latitude, latitude = a)
```


## percentage 

```{r}
percentage_count = ufo %>% 
  filter(country == "USA") %>% 
  select(state, city, longitude, latitude) %>% 
  group_by(state, city, longitude, latitude) %>% 
  summarize(n = n()) %>% 
  arrange(n) 
count_all = percentage_count %>% 
  nrow() %>% 
  as.numeric()
percent_calc = function(num){
  count_num = percentage_count %>% 
    filter(n == num) %>% 
    nrow()
  percent = count_num / count_all
  percent
}
percent = percentage_count %>% 
  group_by(n) %>% 
  summarize(count = n()) %>% 
  mutate(percent = (count / count_all) * 100) %>% 
  filter(n < 100) %>% 
  ggplot(aes(x = n, y = percent)) +
  geom_point() +
  geom_line()

percent
```


## map

```{r}
plot_map_below25 = ufo %>% 
  filter(country == "USA") %>% 
  select(state, city, longitude, latitude) %>% 
  group_by(state, city, longitude, latitude) %>% 
  summarize(n = n()) %>% 
  filter(n <= 25) %>% 
  plot_geo(locationmode = "USA-states", sizes = c(1, 250)) %>% 
  add_markers(
    x = ~latitude, y = ~longitude, group = ~city, color = ~n, hoverinfo = "text",
    text = ~ paste0(city, "<br />", state, ", <br />", n, " times seen UFO")
  ) %>% 
  colorbar(limits = c(0, 100))

plot_map_above25 = ufo %>% 
  filter(country == "USA") %>% 
  select(state, city, longitude, latitude) %>% 
  group_by(state, city, longitude, latitude) %>% 
  summarize(n = n()) %>% 
  filter(n > 25) %>% 
  plot_geo(locationmode = "USA-states", sizes = c(1, 250)) %>% 
  add_markers(
    x = ~latitude, y = ~longitude, group = ~city, color = ~n, hoverinfo = "text",
    text = ~ paste0(city, "<br />", state, ", <br />", n, " times seen UFO")
  ) %>% 
  colorbar(limits = c(50, 550))

plot_map_below25
plot_map_above25
```

## leaflet version

Map for cities with UFO occurred less than 25 times. Markers size (radius) represents the frequency of UFO (n).

```{r}
map_ufo_under25 = ufo %>% 
  filter(country == "USA") %>% 
  select(state, city, longitude, latitude) %>% 
  group_by(state, city, longitude, latitude) %>% 
  summarize(n = n()) %>% 
  filter(n <= 25)
map_under25 = leaflet(data = map_ufo_under25) %>% 
  addTiles() %>% 
  addCircleMarkers(
    radius = ~n/10,
    ~latitude, 
    ~longitude, 
    popup = ~paste0(city, "<br />", state, ", <br />", n)
  )
map_under25
```


Map for cities with UFO occurred more than 25 times. Markers' size (radius) represents the frequency of UFO (n), and 7 cities with UFO occurred more than 300 times were labelled in red.

```{r}
map_ufo_above25 = ufo %>% 
  filter(country == "USA") %>% 
  select(state, city, longitude, latitude) %>% 
  group_by(state, city, longitude, latitude) %>% 
  summarize(n = n()) %>% 
  filter(n > 25)
map_above25 = leaflet(data = map_ufo_above25) %>% 
  addTiles() %>% 
  addCircleMarkers(
    radius = ~n/100, 
    color = ~ifelse(n > 300, "red", "navy"),
    ~latitude, 
    ~longitude, 
    popup = ~paste0(city, "<br />", state, ", <br />", n)
  )
map_above25
```

