---
title: "Length Time Regression"
author: "Jingyi Tang, Jungang Zou"
date: "11/13/2019"
output: html_document
---

## set up

```{r}
# knitr will run the chunk but not include the chunk in the final document
# copy from Jeff

# ensure reproductivity
set.seed(10)

# load library
library(tidyverse)
library(viridis)
library(ggridges)
library(patchwork)
library(rvest)
library(modelr)
library(mgcv)

knitr::opts_chunk$set(
  # display the code in the code truck above its results in the final document
  echo = TRUE,
  # do not display any warning messages generated by the code
  warning = FALSE,
  # set the figure to be 8 x 6, and the proportion it takes to be 90%
  fig.width = 8,
  fig.height = 6, 
  out.width = "90%"
)

# setting a global options for continuous data color family and a different format to set discrete data to have a color family
options(
  ggplot2.countinuous.colour = "hue",
  ggplot2.countinuous.fill = "hue"
)

scale_colour_discrete = scale_color_hue#  scale_colour_viridis_d
scale_fill_discrete = scale_fill_hue#  _viridis_d

# have a minimal theme and legends at the bottom
theme_set(theme_get() + theme(legend.position = "bottom"))

```

## read dataset
```{r}
ufo_data = read_csv(file = "./data/tidied_data_final.csv")


ufo =
  ufo_data %>%  
  filter(country == "USA") %>% 
  #na.omit(ufo_data) %>% 
  separate(date_time, into = c( "date","time"), sep = " " ) %>%
  separate(date, into = c("month","day","year"), sep = "/") %>% 
  separate(time, into = c("hour","minute"), sep = ":") %>% 
  mutate(month = as.factor(month.name[as.numeric(month)]), year = as.numeric(year), hour = as.numeric(hour), minute = as.numeric(minute), day = as.numeric(day), country = as.factor(country), state = as.factor(state), city = as.factor(city)) %>% 
  mutate(add = paste(state, city)) %>% 
  select(year, month, day, hour, minute,  add , encounter_length) %>% 
  na.omit()

```
  
  
```{r}
x_process = function(df){
  x = 
    df %>% 
    select(-encounter_length) %>% 
    model.matrix( ~ ., .)
  x
}



# make the response variables
y_process = function(df){
  y = 
    df %>% 
    select(encounter_length) %>% 
    pull(encounter_length)
  y
}
# here we use mean of square error as the cost function.
lasso_fit = 
  glmnet::glmnet(x = x_process(ufo), y = y_process(ufo), alpha = 1) %>%  #alpha is the parameters to control the type of elastic net models, when alpha = 1, the elastic net model is equivalent to lasso.
  broom::tidy(.)


# draw the plot
#lasso_fit %>%
#  filter(term != "(Intercept)") %>% 
#  ggplot(aes(x = lambda, estimate, color = term)) + 
#  geom_line() + 
#  scale_x_reverse() +
#  labs(
#    title = "Lineplot of the Lasso Estimated Coefficients for Different Lambda",
#    x = "Lambda",
#    y = "Estimated Coefficients",
#    caption = "Data from URL: https://p8105.com/data/birthweight.csv") +
#  theme(plot.title = element_text(hjust = 0.5))

lambda_best = 
  glmnet::cv.glmnet(x = x_process(ufo), y = y_process(ufo), alpha = 1, nfolds = 10)

# display the result
lambda_best


lambda = lambda_best$lambda.min

lasso_best_fit = 
  glmnet::glmnet(x = x_process(ufo), y = y_process(ufo), alpha = 1, nlambda = 1, lambda = lambda) #alpha is the parameters to control the type of elastic net models, when alpha = 1, the elastic net model is equivalent to lasso.

# display the parameters
glmnet::coef.glmnet(lasso_best_fit) 

```


## Checking Test Assumptions

```{r Homogeneity of variance}

#bartlett.test()

```

