---
title: "proposal"
author: "Jingyi Tang, jt3174; Jiafei Li, jl5548"
date: "November 4, 2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Tentative project title

What?!! You said there was an UFO???

## Motivation for this project

We are instantly drawn to the UFO dataset and would like to explore through data to deliver a rigorous and interesting analysis on the data to answer several questions that might spark. 

## Intended final products

We are interested to find out whether there is any relationship between state and UFO's. For example, whether all states share the same probability of sighting an UFO and what kind of UFO. For another example, we can test whether for each state each year, the average times of sighting an UFO are roughly the same. 

## Anticipated data sources

Our data comes from tidytuesday weekly project, which encourages new and experienced users to use the tidyverse tools to analyze data sets that change every week. Our dataset is [UFP Sightings around the world](https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-06-25). 

## Planned analyses / visualizations / coding challenges

Our team is trying to attack the problem with multiple angles. For starters, we are going to tidy data and visualize data. We are interetsed in demostrate the data geographically as a highlight of the visualization. The next step is to find two interesting questions to be answered for the dataset and then we would like to perform two analysis to provide some insight for each, such as regression for the continuous data portion and a categorical analysis for the categorical data part. The continuous data part, we would like to conduct an ANOVA test on year and sighting time for each state. The third part, which is an attempt to make our project to be meaningful and practical, we are currently interested in making a prediction or perform an outlier detection for the dataset depending on which question we will ask in the project. 


## Planned timeline



## Credits

* Finding the dataset: Jungang Zou
* Intended Analysis Methods: Ran Wang
* Writing the proposal: Keyi Wang, Jiafei Li, Jingyi Tang