---
title: "US Frequency Map"
output: 
  flexdashboard::flex_dashboard:
    orientation: column
    vertical_layout: fill 
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(leaflet)
rsconnect::setAccountInfo(name='ljf123-final',
			  token='2D3CCCE4B6471B1C1EE6D2236959DEAB',
			  secret='fJ9Z9UzAv8wgVhnKcfqzX+jBrn1wUdB5SqfFopGl')
```

```{r import, include=FALSE}
# data import and cleaning
ufo_data =
  read_csv("./data/tidied_data_final.csv", na = "") %>% 
  select(-X12)

ufo =
  ufo_data %>%  
  separate(date, into = c("month","day","year"), sep = "/") %>% 
  mutate(a = longitude, longitude = latitude, latitude = a) %>% 
  filter(country == "USA") %>% 
  select(latitude, longitude, state, city) %>% 
  group_by(latitude, longitude, state, city) %>% 
  summarize(n = n())
```

Column {.sidebar}
-----------------------------------------------------------------------
This dashboard reveals the number of times UFO appeared in each city in US. The size (radius) of circle markers corresponds to the frequency of UFO appearance in the city.

Users can adjust the frequency range (minimum number UFO appeared, maximum number UFO appeared) to see which cities in US had UFO appeared the input number of times. The frequency map is revealing cities with UFO appeared 25 to 300 times by default.

The focus points are marked in red, revealing cities with UFO appeared more than the input number of times. By default, the focus point input was set as 300, and 7 cities with UFO appeared more than 300 times are marked in red, while others in navy.


```{r sidebar, echo=FALSE}
# set the max and min frequency for range
min_frequency = 1
max_frequency = 600
# sliderInput widget
sliderInput(
  "frequency_range", 
  label = h3("Choose frequency range"), 
  min = min_frequency, max = max_frequency, value = c(25, 300))

# set choice list for focus points
min_focus = 100
max_focus = 300
# sliderInput widget
sliderInput(
  "focus_choice", 
  label = h3("Choose focus point minimum value"), 
  min = min_focus, max = max_focus, value = 300)
```

Column 
-----------------------------------------------------------------------

### US Frequency Map

```{r chartA, echo=FALSE}
renderLeaflet({
  ufo %>% 
    filter(n %in% input$frequency_range[1]:input$frequency_range[2]) %>% 
    leaflet() %>% 
    addTiles() %>% 
    addCircleMarkers(
      radius = ~n/100,
      color = ~ifelse(n > input$focus_choice, "red", "navy"),
      ~latitude,
      ~longitude,
      label = ~paste0(city, " ", state, ", ", n, " times seen UFO")
    )
})
```


