---
title: "Predicting UFO"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
# ensure reproductivity
set.seed(10)

# load library


library(flexdashboard)
library(tidyverse)
library(viridis)
library(leaflet)    
library(viridis)
library(ggridges)
library(patchwork)
library(rvest)
library(MLmetrics)
library(e1071)
library(tidyverse)

rsconnect::setAccountInfo(name='ljf123-final',
			  token='2D3CCCE4B6471B1C1EE6D2236959DEAB',
			  secret='fJ9Z9UzAv8wgVhnKcfqzX+jBrn1wUdB5SqfFopGl')
```


```{r import, include=FALSE}
# data import and cleaning
ufo_data = read_csv("./data/tidied_data_final.csv", na = "")

ufo_usa =
  ufo_data %>%  
  separate(time, into = c("hour", "minute"), sep = ":") %>% 
  separate(date, into = c("month","day","year"), sep = "/") %>% 
  mutate(a = longitude, longitude = latitude, latitude = a) %>% 
  filter(country == "USA") %>% 
  select(latitude, longitude, state, city, year, month, day, hour, minute) 




ufo_frequncy = ufo_usa %>% 
  group_by(latitude, longitude, state, city) %>% 
  summarize(n = n())

ufo_usa = ufo_usa %>% 
  mutate(city_state = paste(state, city, sep = " ")) %>% 
  select(-city, -state) %>% 
  dplyr::group_by(city_state) %>% 
  mutate(count = dplyr::n()) %>% 
  filter(count >= 100) %>% 
  ungroup() %>% 
  select(-count) %>% 
  mutate(add = as.factor(city_state))
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r sidebar, echo=FALSE}
# set the year list for choices
years = c(1900:2100)
# selectInput widget for year
selectInput(
  "year_choice",
  label = h3("Choose year"),
  choices = years, selected = "2000")

# set the month list for choices
months = month.name
# selectInput widget for month
selectInput(
  "month_choice",
  label = h3("Choose month"),
  choices = months, selected = "January")

# set the day list for choices
days = c(1:31)
# selectInput widget for day
selectInput(
  "day_choice",
  label = h3("Choose day"),
  choices = days, selected = "1")

# set the hour list for choices
hours = ufo_usa %>% distinct(hour) %>% arrange(hour) %>% pull(hour) 
# selectInput widget for hour
selectInput(
  "hour_choice",
  label = h3("Choose hour"),
  choices = hours, selected = "00")

# set the minute list for choices
minutes = ufo_usa %>% distinct(minute) %>% arrange(minute) %>% pull(minute) 
# selectInput widget for hour
selectInput(
  "minute_choice",
  label = h3("Choose minute"),
  choices = minutes, selected = "00")

# set the city_state list for choices
city_states = ufo_usa %>% distinct(city_state) %>% pull(city_state)  
# selectInput widget (dropdown menu) for city_state
selectInput(
  "city_state_choice", 
  label = h3("Select city-state"),
  choices = city_states, selected = "Brooklyn NY")
```

Column 
-----------------------------------------------------------------------

### Predicting whether UFO will appear in the chosen place and time

```{r chartA, echo=FALSE, message=FALSE, warning = FALSE}


# transform each levels in factors to new variables to form the input of SVM
factor_variable_cope = function(df){
    if (is_tibble(df)) {
      df = as.data.frame(df)
    }
    for (i in colnames(df[, sapply(df, is.factor)])) {
      for (level in unique(df[, i])) {
          df[paste(i, level, sep = "_")] = 
              as.integer(ifelse(df[, i] == level, 1, -1))
      }
    }
    df
}

ufo_data = read_csv(file = "./data/tidied_data_final.csv")



# data tidy for prediction
ufo =
  ufo_data %>%  
  filter(country == "USA") %>% 
  separate(date, into = c("month","day","year"), sep = "/") %>% 
  separate(time, into = c("hour","minute"), sep = ":") %>% 
  select(year, month, day, hour, minute,state, city) %>%
  na.omit(ufo_data) %>% 
  mutate(add = paste(state, city)) %>% 
  mutate(month = as.factor(month.name[as.numeric(month)]), year = as.numeric(year), hour = as.numeric(hour), minute = as.numeric(minute), day = as.numeric(day))


renderLeaflet({
  sample = tibble(add = as.character(input$city_state_choice), year = as.numeric(input$year_choice), month = as.character(input$month_choice), day = as.numeric(input$day_choice), hour = as.numeric(input$hour_choice), minute = as.numeric(input$minute_choice))

  svm_model = readRDS("./SVM.rds")
  
  
  #svm = 
  #  ufo_data %>% 
  #  mutate(month = month.name[as.numeric(month)]) %>% 
  #  bind_rows(sample, .) %>% 
  #  mutate(year = as.numeric(year),  hour = as.numeric(hour), minute = as.numeric(minute), day = as.numeric(day)) %>% 
  #  mutate(month = as.factor(month)) %>% 
  #  dplyr::group_by(add) %>% 
  ##  mutate(count = dplyr::n()) %>% 
  #  filter(count >= 100) %>% 
  #  ungroup() %>% 
  #  select(-count) %>% 
  #  mutate(add = as.factor(add)) %>% 
  #  as.data.frame() %>% 
  #  factor_variable_cope() %>% 
  #  slice(1) %>% 
  #  select(-month, -add) %>% 
  
   svm = 
    ufo %>% 
    select(year, month, day, hour, minute,state, city) %>%
    na.omit(ufo_data) %>% 
    mutate(add = paste(state, city)) %>% 
    mutate(year = as.numeric(year), month = month.name[as.numeric(month)], hour = as.numeric(hour), minute = as.numeric(minute), day = as.numeric(day)) %>% 
    select(-city, -state) %>% 
    bind_rows(., sample) %>% 
    mutate(month = as.factor(month)) %>% 
    dplyr::group_by(add) %>% 
    mutate(count = dplyr::n()) %>% 
    filter(count >= 100) %>% 
    ungroup() %>% 
    select(-count) %>% 
    mutate(add = as.factor(add)) %>% 
    as.data.frame() %>% 
    factor_variable_cope() %>% 
    slice(nrow(.)) %>% 
    select(-month, -add) %>% 
    mutate(year = as.integer(year), day = as.integer(day), hour = as.integer(hour), minute = as.integer(minute))
  
 
  
  svm_result =
    predict(svm_model, as.data.frame(svm))
  
  svm_result =
    ufo_usa %>% 
    filter(city_state == input$city_state_choice) %>% 
    select(latitude, longitude, city_state) %>%
    distinct() %>% 
    mutate(svm = svm_result) 
  
  svm_result %>% 
    leaflet() %>% 
    addTiles() %>% 
    addCircleMarkers(
      color = ~if_else(svm_result$svm == TRUE, "blue", "red"),
      ~latitude,
      ~longitude
    )
})
```

