---
title: "visualization"
author: "Keyi Wang"
date: "11/8/2019"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(leaflet)
library(dplyr)
library(ggplot2)
library(ggmap)
library(sf)
library(mapview)
library(rgdal)
library(htmltools)


knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 8,
  fig.height = 6, 
  out.width = "90%"
)


options(
  ggplot2.countinuous.colour = "viridis",
  ggplot2.countinuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))

```

## reading data
```{r}
ufo_data = readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-06-25/ufo_sightings.csv")

ufo =
ufo_data %>%  
na.omit(ufo_data) %>% 
separate(date_time, into = c( "date","time"), sep = " " ) %>%
separate( date, into = c("month","day","year"), sep = "/") %>% 
mutate(country = recode(country , 
                        "us" = "the United State", 
                        "au" = "Australia",
                        "gb" = "the United Kingdom",
                        "ca" = "Canada")) 
```


```{r}
## A bargraph showing the total number of UFO observed among 4 countries. As the number of UFO  observed in Australia and Britain is really low, for later graphs, we decided to omit data in these two countries.

ufo %>%
  group_by(country) %>%
  count() %>%
 mutate(precentage = n/66516) %>%
ggplot(aes(x = country, y = precentage , fill = country, label =  scales::percent(precentage))) + 
    geom_col(position = 'dodge') + 
    geom_text(position = position_dodge(width = .9),  
              vjust = -0.5,   size = 3) + 
    labs(title = "Bargraph of the precentage of UFO Observed by Country",
         x = "Country",y = "Precentage") 



```

```{r}
## line plot showing the number of UFO observed across time among countries

ufo %>%
group_by(year) %>%
count(country) %>%
ungroup() %>%
mutate(year = as.numeric(year)) %>%
  ggplot(aes(x = year,y = n,group = country)) +
  geom_line(aes(color = country)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(
title = " Line Plot of Number of UFO Observed Across Time Among different Countries ",
    x = "Year",
    y = "Number Of UFO Observed"
  )


```


```{r}
### Boxplot showing the distribution of the UFO Shape Observed in US
  
ufo %>%
  filter(country == "the United State")%>%
  group_by(state) %>%
  count(ufo_shape) %>%
  arrange(desc(n)) %>% 
  ungroup %>% 
  mutate(
  ufo_shape = factor(ufo_shape),
  ufo_shape = forcats::fct_reorder(ufo_shape, n)) %>%
  ggplot(aes(x = ufo_shape, y = n, group = ufo_shape)) +
  geom_boxplot(aes(color =ufo_shape)) +
  theme(axis.text.x = element_text(angle = 300)) +
  labs(
    title = "Boxplot showing distribution of the UFO Shape Observed in US ",
    x = "UFO Shape",
    y = "Number"
  )
```


```{r include=FALSE}
US =
ufo %>%
  filter(country == "the United State")%>%
  filter(year == "2010") %>%
  select(state, city_area,latitude,longitude,
         encounter_length)%>%   
  mutate(observed_min = round(encounter_length/60)
         )%>%
  arrange(desc(observed_min))%>%
  select(-encounter_length) %>%
  group_by(state)%>%
  summarise(Num.observed = n())

states = readOGR("data/cb_2018_us_state_500k.shp")

#check for the matching bewtween shapefile and my US dataset
is.element(US$state,tolower(states$STUSPS))
is.element(tolower(states$STUSPS),US$state)

# missing 14,38,39,46,45 so to create new_states df with only matching states
new_states = subset(states, is.element(tolower(states$STUSPS),US$state))
is.element(tolower(new_states$STUSPS),US$state)
is.element(US$state,tolower(new_states$STUSPS))

## make it into same order
US = US[order(match(US$state, tolower(new_states$STUSPS))),]

# set for the range based on number being observed--discrete
# bins = c(0,50,100,150,200,250,300,350,400,450,500,550)
# pal = colorBin("YlOrRdBu",domain = US$Num.observed,bins = bins)
 
pal <- colorNumeric(palette = "Reds",domain = US$Num.observed)
labels = paste( "<p>","Number Of UFO Observed in Year 2010：", US$Num.observed,"<p>",sep = "")
  map = leaflet() %>%
  setView(-96,37.8,4)%>%
  addTiles() %>%
  addPolygons(data = states,
              weight = 1,smoothFactor = 0.2,
              color = "white",fillOpacity = 1,
              fillColor = pal(US$Num.observed),
              label = lapply(labels, HTML)
              )%>%
    addLegend(pal = pal,
              values = US$Num.observed,
              opacity = 0.7,
              position = "topright")
```


