---
title: "visualization"
author: "Keyi Wang, Jingyi Tang"
date: "11/8/2019"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(plotly)

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 8,
  fig.height = 6, 
  out.width = "90%"
)


options(
  ggplot2.countinuous.colour = "viridis",
  ggplot2.countinuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))

```

## reading data
```{r}
ufo_data = readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-06-25/ufo_sightings.csv")
```


## Number of UFO observed across time among 4 countries --Line Plot
```{r}
line_plot =
ufo_data %>%  
na.omit(ufo_data) %>% ## omit missing data
separate(date_time, into = c( "date","time"), sep = " " ) %>%
separate( date, into = c("month","day","year"), sep = "/") %>%
mutate(year = as.numeric(year)) %>% 
group_by(year) %>%
count(country) %>%
  ggplot(aes(x = year,y = n,group = country)) +
  geom_line(aes(color = country)) +
  theme(axis.text.x = element_text (angle = 90)) +
  scale_x_continuous(breaks = c(1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020)) +
  labs(
    title = " Line Plot of Number of UFO Observed Across Time Among different Countries",
    x = "Year",
    y = "Number Of UFO Observed"
  )
  ggplotly(line_plot)

```

