---
title: "Visualization Jingyi"
author: "Jingyi"
date: "11/9/2019"
output: html_document
---

```{r}

# knitr will run the chunk but not include the chunk in the final document

# ensure reproductivity
set.seed(1)

# load library
library(tidyverse)
library(viridis)
library(ggridges)

knitr::opts_chunk$set(
  # display the code in the code truck above its results in the final document
  echo = TRUE,
  # do not display any warning messages generated by the code
  warning = FALSE,
  # set the figure to be 8 x 6, and the proportion it takes to be 90%
  fig.width = 8,
  fig.height = 6, 
  out.width = "90%"
)

# setting a global options for continuous data color family and a different format to set discrete data to have a color family
options(
  ggplot2.countinuous.colour = "viridis",
  ggplot2.countinuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

# have a minimal theme and legends at the bottom
theme_set(theme_minimal() + theme(legend.position = "bottom"))

```


```{r read data}

ufo_data = readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-06-25/ufo_sightings.csv")

ufo = ufo_data %>%  
  na.omit(ufo_data) %>% 
  separate(date_time, into = c("date","time"), sep = " " ) %>%
  separate(date, into = c("month","day","year"), sep = "/") 

```

```{r Length Descriptive Data}

Length = ufo %>% 
  mutate(ufo_shape = forcats::fct_reorder(ufo_shape, encounter_length),
         country = recode(country, "us" = "the United States", 
                          "au" = "Australia",
                          "gb" = "the United Kingdom",
                          "ca" = "Canada")) %>% 
  select(country, encounter_length) %>% 
  group_by(country) %>% 
  summarize(mean = mean(encounter_length),
            median = median(encounter_length),
            sd = sd(encounter_length),
            Q1 = quantile(encounter_length, 0.25),
            Q3 = quantile(encounter_length, 0.75),
            IQR = IQR(encounter_length)) %>% 
  # arrange according to sales for each group
  arrange(desc(mean)) %>% 
  # knit a table
  knitr::kable(digits = 2)
  
  #ggplot(aes(x = encounter_length, fill = country)) +
  #geom_density(alpha = 0.4, adjust = 0.5)

```

